[target.'cfg(all())']
rustflags = [
    "-W", "clippy::pedantic",
    "-A", "clippy::missing_errors_doc",
    "-A", "clippy::module_name_repetitions",
    "-A", "clippy::unreadable_literal",
    "-A", "clippy::must_use_candidate",
    "-A", "clippy::return_self_not_must_use",
    "-A", "clippy::doc_markdown",
    "-A", "clippy::doc_link_with_quotes",
]
